package view;

public class Search extends javax.swing.JFrame {

    /**
     * Creates new form Edit
     */
    public Search() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitle = new javax.swing.JLabel();
        textFieldTitle = new javax.swing.JTextField();
        labelDescription = new javax.swing.JLabel();
        scrollPaneTextArea = new javax.swing.JScrollPane();
        textAreaDescription = new javax.swing.JTextArea();
        buttonEdit = new javax.swing.JButton();
        textFieldId = new javax.swing.JTextField();
        labelId = new javax.swing.JLabel();
        buttonBack = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("TITLE");

        textFieldTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldTitleActionPerformed(evt);
            }
        });

        labelDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDescription.setText("DESCRIPTION");

        textAreaDescription.setColumns(20);
        textAreaDescription.setRows(5);
        scrollPaneTextArea.setViewportView(textAreaDescription);

        buttonEdit.setText("EDIT");
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        textFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldIdActionPerformed(evt);
            }
        });

        labelId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelId.setText("ID");

        buttonBack.setText("BACK");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        buttonDelete.setText("DELETE");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        buttonSearch.setText("SEARCH");
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(buttonEdit)
                                .addGap(18, 18, 18)
                                .addComponent(buttonDelete)
                                .addGap(17, 17, 17)
                                .addComponent(buttonBack))
                            .addComponent(labelDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scrollPaneTextArea)
                            .addComponent(textFieldTitle)
                            .addComponent(textFieldId)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(buttonSearch)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(scrollPaneTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEdit)
                    .addComponent(buttonBack)
                    .addComponent(buttonDelete))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldTitleActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEditActionPerformed

    private void textFieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldIdActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JLabel labelDescription;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JScrollPane scrollPaneTextArea;
    private javax.swing.JTextArea textAreaDescription;
    private javax.swing.JTextField textFieldId;
    private javax.swing.JTextField textFieldTitle;
    // End of variables declaration//GEN-END:variables
    
    public javax.swing.JButton getButtonBack() {
        return buttonBack;
    }

    public void setButtonBack(javax.swing.JButton buttonBack) {
        this.buttonBack = buttonBack;
    }

    public javax.swing.JButton getButtonDelete() {
        return buttonDelete;
    }

    public void setButtonDelete(javax.swing.JButton buttonDelete) {
        this.buttonDelete = buttonDelete;
    }

    public javax.swing.JButton getButtonEdit() {
        return buttonEdit;
    }
    
    public javax.swing.JButton getButtonSearch() {
        return buttonSearch;
    }

    public void setButtonEdit(javax.swing.JButton buttonEdit) {
        this.buttonEdit = buttonEdit;
    }
    
    public void setButtonSearch(javax.swing.JButton buttonSearch) {
        this.buttonSearch = buttonSearch;
    }

    public javax.swing.JLabel getLabelDescription() {
        return labelDescription;
    }

    public void setLabelDescription(javax.swing.JLabel labelDescription) {
        this.labelDescription = labelDescription;
    }

    public javax.swing.JLabel getLabelId() {
        return labelId;
    }

    public void setLabelId(javax.swing.JLabel labelId) {
        this.labelId = labelId;
    }

    public javax.swing.JLabel getLabelTitle() {
        return labelTitle;
    }

    public void setLabelTitle(javax.swing.JLabel labelTitle) {
        this.labelTitle = labelTitle;
    }

    public javax.swing.JScrollPane getScrollPaneTextArea() {
        return scrollPaneTextArea;
    }

    public void setScrollPaneTextArea(javax.swing.JScrollPane scrollPaneTextArea) {
        this.scrollPaneTextArea = scrollPaneTextArea;
    }

    public javax.swing.JTextArea getTextAreaDescription() {
        return textAreaDescription;
    }

    public void setTextAreaDescription(javax.swing.JTextArea textAreaDescription) {
        this.textAreaDescription = textAreaDescription;
    }

    public javax.swing.JTextField getTextFieldId() {
        return textFieldId;
    }

    public void setTextFieldId(javax.swing.JTextField textFieldId) {
        this.textFieldId = textFieldId;
    }

    public javax.swing.JTextField getTextFieldTitle() {
        return textFieldTitle;
    }

    public void setTextFieldTitle(javax.swing.JTextField textFieldTitle) {
        this.textFieldTitle = textFieldTitle;
    }
}
